# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(950, 278)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 210, 151, 32))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 88, 27))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 91, 121))
        self.groupBox.setObjectName("groupBox")
        self.interval = QtWidgets.QSpinBox(self.groupBox)
        self.interval.setGeometry(QtCore.QRect(10, 40, 71, 28))
        self.interval.setObjectName("interval")
        self.maxxaxis = QtWidgets.QSpinBox(self.groupBox)
        self.maxxaxis.setGeometry(QtCore.QRect(10, 90, 71, 28))
        self.maxxaxis.setObjectName("maxxaxis")
        self.interval_label = QtWidgets.QLabel(self.groupBox)
        self.interval_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.interval_label.setObjectName("interval_label")
        self.maxxaxis_label = QtWidgets.QLabel(self.groupBox)
        self.maxxaxis_label.setGeometry(QtCore.QRect(10, 70, 66, 19))
        self.maxxaxis_label.setObjectName("maxxaxis_label")
        self.MplWidget = MplWidget(Dialog)
        self.MplWidget.setGeometry(QtCore.QRect(299, -1, 601, 231))
        self.MplWidget.setObjectName("MplWidget")
        self.label_timer = QtWidgets.QLabel(Dialog)
        self.label_timer.setGeometry(QtCore.QRect(20, 0, 161, 19))
        self.label_timer.setObjectName("label_timer")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(10, 210, 100, 28))
        self.saveButton.setObjectName("saveButton")
        self.statsGroupBox = QtWidgets.QGroupBox(Dialog)
        self.statsGroupBox.setGeometry(QtCore.QRect(160, 30, 130, 200))
        self.statsGroupBox.setObjectName("statsGroupBox")
        self.statsLayout = QtWidgets.QVBoxLayout(self.statsGroupBox)
        self.statsLayout.setObjectName("statsLayout")
        self.meanLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.meanLabel.setObjectName("meanLabel")
        self.statsLayout.addWidget(self.meanLabel)
        self.meanXLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.meanXLabel.setObjectName("meanXLabel")
        self.statsLayout.addWidget(self.meanXLabel)
        self.meanYLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.meanYLabel.setObjectName("meanYLabel")
        self.statsLayout.addWidget(self.meanYLabel)
        self.meanZLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.meanZLabel.setObjectName("meanZLabel")
        self.statsLayout.addWidget(self.meanZLabel)
        self.stdLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.stdLabel.setObjectName("stdLabel")
        self.statsLayout.addWidget(self.stdLabel)
        self.stdXLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.stdXLabel.setObjectName("stdXLabel")
        self.statsLayout.addWidget(self.stdXLabel)
        self.stdYLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.stdYLabel.setObjectName("stdYLabel")
        self.statsLayout.addWidget(self.stdYLabel)
        self.stdZLabel = QtWidgets.QLabel(self.statsGroupBox)
        self.stdZLabel.setObjectName("stdZLabel")
        self.statsLayout.addWidget(self.stdZLabel)
        self.simulate_button = QtWidgets.QPushButton(Dialog)
        self.simulate_button.setGeometry(QtCore.QRect(110, 60, 31, 27))
        self.simulate_button.setObjectName("simulate_button")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.interval_label.setText(_translate("Dialog", "Interval (s)"))
        self.maxxaxis_label.setText(_translate("Dialog", "Max x"))
        self.label_timer.setText(_translate("Dialog", "Status: Not Connected"))
        self.saveButton.setText(_translate("Dialog", "Save to CSV"))
        self.statsGroupBox.setTitle(_translate("Dialog", "Statistics"))
        self.meanLabel.setText(_translate("Dialog", "Mean:"))
        self.meanXLabel.setText(_translate("Dialog", "X: 0.0000"))
        self.meanYLabel.setText(_translate("Dialog", "Y: 0.0000"))
        self.meanZLabel.setText(_translate("Dialog", "Z: 0.0000"))
        self.stdLabel.setText(_translate("Dialog", "Std Dev:"))
        self.stdXLabel.setText(_translate("Dialog", "X: 0.0000"))
        self.stdYLabel.setText(_translate("Dialog", "Y: 0.0000"))
        self.stdZLabel.setText(_translate("Dialog", "Z: 0.0000"))
        self.simulate_button.setText(_translate("Dialog", "S"))
from mplwidget import MplWidget
